name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 10.11.0

    - uses: actions/setup-node@v4
      with:
        node-version: 20.12.0
        cache: "pnpm"

    - shell: bash
      run: pnpm add -g turbo

    - shell: bash
      run: pnpm install --frozen-lockfile
