#!/usr/bin/env bash
# Initializes a Claude Code worktree: copies env files from the main checkout
# and installs dependencies. Runs on SessionStart (startup).
#
# Safe in the main checkout — only acts when running inside a worktree under
# .claude/worktrees/. Logs are informational; failures are non-fatal so a
# broken hook can't block a session from starting.

set -uo pipefail

# Only run inside a Claude worktree
WORKTREE_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
if [[ -z "$WORKTREE_ROOT" ]] || [[ "$WORKTREE_ROOT" != *".claude/worktrees/"* ]]; then
  exit 0
fi

# Resolve the main checkout (first entry in `git worktree list`).
# Use sub() instead of $2 so paths containing spaces aren't truncated.
MAIN_CHECKOUT=$(git worktree list --porcelain | awk '/^worktree /{sub(/^worktree /, ""); print; exit}')
if [[ -z "$MAIN_CHECKOUT" ]] || [[ "$MAIN_CHECKOUT" == "$WORKTREE_ROOT" ]]; then
  echo "worktree-init: could not resolve main checkout, skipping" >&2
  exit 0
fi

cd "$WORKTREE_ROOT" || { echo "worktree-init: cd to $WORKTREE_ROOT failed, skipping" >&2; exit 0; }

# Compute an initial port offset (1-99) from the worktree name, then probe for
# a free port pair. Starting from the hash keeps allocation stable when ports
# are free; probing avoids collisions when two worktree names hash to the same
# offset or when a port is already in use.
WORKTREE_NAME=$(basename "$WORKTREE_ROOT")
START_OFFSET=$(printf '%s' "$WORKTREE_NAME" | cksum | awk '{print ($1 % 99) + 1}')

port_free() {
  # Pure-bash probe: /dev/tcp connect fails iff nothing is listening.
  ! (exec 3<>/dev/tcp/127.0.0.1/"$1") 2>/dev/null
}

PORT_OFFSET=""
for i in $(seq 0 98); do
  offset=$(( (START_OFFSET - 1 + i) % 99 + 1 ))
  if port_free $((3000 + offset)) && port_free $((8081 + offset)); then
    PORT_OFFSET=$offset
    break
  fi
done
if [[ -z "$PORT_OFFSET" ]]; then
  echo "worktree-init: no free port pair in 3001-3099/8082-8180; using hash offset" >&2
  PORT_OFFSET=$START_OFFSET
fi
WEB_PORT=$((3000 + PORT_OFFSET))
METRO_PORT=$((8081 + PORT_OFFSET))

# Copy env files from main checkout (only if missing locally)
copied=()
for rel in .env .env.local .env.preview .env.production apps/expo/.env apps/web/.env.local; do
  src="$MAIN_CHECKOUT/$rel"
  dst="./$rel"
  if [[ -f "$src" && ! -f "$dst" ]]; then
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    copied+=("$rel")
  fi
done

if [[ ${#copied[@]} -gt 0 ]]; then
  echo "worktree-init: copied env files: ${copied[*]}" >&2
fi

# Apply per-worktree port isolation exactly once (gated by marker in .env.local)
if [[ -f .env.local ]] && ! grep -q "^# worktree-ports" .env.local; then
  for rel in .env.local apps/expo/.env apps/web/.env.local; do
    [[ -f "$rel" ]] || continue
    sed -i.bak \
      -e "s|localhost:3000|localhost:${WEB_PORT}|g" \
      -e "s|127\.0\.0\.1:3000|127.0.0.1:${WEB_PORT}|g" \
      -e "s|localhost:8081|localhost:${METRO_PORT}|g" \
      "$rel"
    rm -f "$rel.bak"
  done
  {
    echo ""
    echo "# worktree-ports (auto-generated by .claude/hooks/worktree-init.sh)"
    echo "PORT=${WEB_PORT}"
    echo "RCT_METRO_PORT=${METRO_PORT}"
  } >> .env.local
  # Rewrite .claude/launch.json so `preview_start` picks the right port.
  # Use --skip-worktree so the local port rewrite doesn't pollute `git status`
  # or get committed from this worktree.
  if [[ -f .claude/launch.json ]]; then
    sed -i.bak \
      -e "s|\"port\": 3000|\"port\": ${WEB_PORT}|g" \
      -e "s|\"port\": 8081|\"port\": ${METRO_PORT}|g" \
      .claude/launch.json
    rm -f .claude/launch.json.bak
    git update-index --skip-worktree .claude/launch.json 2>/dev/null || true
  fi
  echo "worktree-init: assigned ports — web=${WEB_PORT}, metro=${METRO_PORT}" >&2
fi

# Install deps if missing
if [[ ! -d node_modules ]]; then
  echo "worktree-init: running pnpm install" >&2
  pnpm install >&2 || echo "worktree-init: pnpm install failed (non-fatal)" >&2
fi

echo "✅ Worktree initialized at $WORKTREE_ROOT"
echo "   web:   http://localhost:${WEB_PORT}"
echo "   metro: http://localhost:${METRO_PORT}"
