#!/usr/bin/env bash
# Initializes a Claude Code worktree: copies env files from the main checkout
# and installs dependencies. Runs on SessionStart (startup).
#
# Safe in the main checkout — only acts when running inside a worktree under
# .claude/worktrees/. Logs are informational; failures are non-fatal so a
# broken hook can't block a session from starting.

set -uo pipefail

# Only run inside a Claude worktree
WORKTREE_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
if [[ -z "$WORKTREE_ROOT" ]] || [[ "$WORKTREE_ROOT" != *".claude/worktrees/"* ]]; then
  exit 0
fi

# Resolve the main checkout (first entry in `git worktree list`).
# Use sub() instead of $2 so paths containing spaces aren't truncated.
MAIN_CHECKOUT=$(git worktree list --porcelain | awk '/^worktree /{sub(/^worktree /, ""); print; exit}')
if [[ -z "$MAIN_CHECKOUT" ]] || [[ "$MAIN_CHECKOUT" == "$WORKTREE_ROOT" ]]; then
  echo "worktree-init: could not resolve main checkout, skipping" >&2
  exit 0
fi

cd "$WORKTREE_ROOT" || { echo "worktree-init: cd to $WORKTREE_ROOT failed, skipping" >&2; exit 0; }

# Assign a unique port pair to this worktree.
#
# Algorithm:
#   1. Acquire a cross-worktree lock (atomic mkdir) rooted at the main
#      checkout, so simultaneous worktree initializations can't pick the
#      same pair via a read-then-assign race.
#   2. Enumerate sibling worktrees' marker files to collect ports already
#      assigned to other worktrees — those are off-limits.
#   3. Start at a hash-derived offset (stable reassignment across restarts)
#      and linear-probe until we find a pair that is neither assigned to
#      a sibling nor currently bound by a listening socket.
#   4. Write our own marker inside the lock so the next initializer sees it.
WORKTREE_NAME=$(basename "$WORKTREE_ROOT")
START_OFFSET=$(printf '%s' "$WORKTREE_NAME" | cksum | awk '{print ($1 % 99) + 1}')

port_free() {
  # Pure-bash probe: /dev/tcp connect fails iff nothing is listening.
  ! (exec 3<>/dev/tcp/127.0.0.1/"$1") 2>/dev/null
}

LOCK_DIR="$MAIN_CHECKOUT/.claude/.worktree-ports.lock"
mkdir -p "$(dirname "$LOCK_DIR")"
lock_acquired=false
for _ in $(seq 1 50); do
  if mkdir "$LOCK_DIR" 2>/dev/null; then
    lock_acquired=true
    trap 'rmdir "$LOCK_DIR" 2>/dev/null || true' EXIT
    break
  fi
  sleep 0.1
done
if ! $lock_acquired; then
  echo "worktree-init: could not acquire port-allocation lock, proceeding without it" >&2
fi

# Collect ports already claimed by sibling worktrees.
assigned_web=" "
assigned_metro=" "
if [[ -d "$MAIN_CHECKOUT/.claude/worktrees" ]]; then
  for marker in "$MAIN_CHECKOUT"/.claude/worktrees/*/.claude/.worktree-ports; do
    [[ -f "$marker" ]] || continue
    [[ "$marker" == "$WORKTREE_ROOT/.claude/.worktree-ports" ]] && continue
    while IFS='=' read -r k v; do
      case "$k" in
        WEB_PORT)   assigned_web+="$v " ;;
        METRO_PORT) assigned_metro+="$v " ;;
      esac
    done < "$marker"
  done
fi

web_claimable()   { case "$assigned_web"   in *" $1 "*) return 1 ;; esac; port_free "$1"; }
metro_claimable() { case "$assigned_metro" in *" $1 "*) return 1 ;; esac; port_free "$1"; }

PORT_OFFSET=""
for i in $(seq 0 98); do
  offset=$(( (START_OFFSET - 1 + i) % 99 + 1 ))
  if web_claimable $((3000 + offset)) && metro_claimable $((8081 + offset)); then
    PORT_OFFSET=$offset
    break
  fi
done
if [[ -z "$PORT_OFFSET" ]]; then
  echo "worktree-init: no unclaimed free port pair; falling back to hash offset" >&2
  PORT_OFFSET=$START_OFFSET
fi
WEB_PORT=$((3000 + PORT_OFFSET))
METRO_PORT=$((8081 + PORT_OFFSET))

# Copy env files from main checkout (only if missing locally)
copied=()
for rel in .env .env.local .env.preview .env.production apps/expo/.env apps/web/.env.local; do
  src="$MAIN_CHECKOUT/$rel"
  dst="./$rel"
  if [[ -f "$src" && ! -f "$dst" ]]; then
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    copied+=("$rel")
  fi
done

if [[ ${#copied[@]} -gt 0 ]]; then
  echo "worktree-init: copied env files: ${copied[*]}" >&2
fi

# Rewrite env files in place (destructive — gated by marker so it runs once).
MARKER=".claude/.worktree-ports"
if [[ ! -f "$MARKER" ]]; then
  for rel in .env.local apps/expo/.env apps/web/.env.local; do
    [[ -f "$rel" ]] || continue
    sed -i.bak \
      -e "s|localhost:3000|localhost:${WEB_PORT}|g" \
      -e "s|127\.0\.0\.1:3000|127.0.0.1:${WEB_PORT}|g" \
      -e "s|localhost:8081|localhost:${METRO_PORT}|g" \
      -e "s|127\.0\.0\.1:8081|127.0.0.1:${METRO_PORT}|g" \
      "$rel"
    rm -f "$rel.bak"
  done
  if [[ -f .env.local ]]; then
    {
      echo ""
      echo "# worktree-ports (auto-generated by .claude/hooks/worktree-init.sh)"
      echo "PORT=${WEB_PORT}"
      echo "RCT_METRO_PORT=${METRO_PORT}"
    } >> .env.local
  fi
  mkdir -p .claude
  printf 'WEB_PORT=%d\nMETRO_PORT=%d\n' "$WEB_PORT" "$METRO_PORT" > "$MARKER"
  echo "worktree-init: env rewrites applied — web=${WEB_PORT}, metro=${METRO_PORT}" >&2
fi

# Generate .claude/launch.json from the committed template on every run.
# This is safe to do repeatedly because the output is deterministic for a
# given port pair, and the file is gitignored so local regeneration can't
# pollute commits or hide upstream changes (which now land in launch.json.example).
if [[ -f .claude/launch.json.example ]]; then
  sed \
    -e "s|\"port\": 3000|\"port\": ${WEB_PORT}|g" \
    -e "s|\"port\": 8081|\"port\": ${METRO_PORT}|g" \
    .claude/launch.json.example > .claude/launch.json
fi

# Release the port-allocation lock now that our marker is written. Doing this
# before `pnpm install` means a concurrent worktree init isn't blocked for
# minutes while we install dependencies.
if $lock_acquired; then
  rmdir "$LOCK_DIR" 2>/dev/null || true
  lock_acquired=false
  trap - EXIT
fi

# Install deps if missing
if [[ ! -d node_modules ]]; then
  echo "worktree-init: running pnpm install" >&2
  pnpm install >&2 || echo "worktree-init: pnpm install failed (non-fatal)" >&2
fi

echo "✅ Worktree initialized at $WORKTREE_ROOT"
echo "   web:   http://localhost:${WEB_PORT}"
echo "   metro: http://localhost:${METRO_PORT}"
