const dataForUsersFor2024Array = [
  {
    user_id: "user_2ZFNoiajf80Q4ZiTQj8hAgatRCt",
    username: "jaronheard",
    total_events_captured: "252",
    unique_event_types: "22",
    most_active_month: "June",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "28",
    first_event_id: "clrbwg21u0001f48lm6x2zsoq",
    first_event_name: "Dig A Hole Zines Fundraising PARTY",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/01/13/4ktjNP7rKz-file.jpeg?crop-x=0&crop-y=87&crop-w=1350&crop-h=1350",
    first_event_date: "2024-01-13 06:00:00",
  },
  {
    user_id: "user_2ZFNp40GcUNt7KKev1IYqlojZHZ",
    username: "joshcarr",
    total_events_captured: "126",
    unique_event_types: "19",
    most_active_month: "October",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "37",
    first_event_id: "clr08f7um0001u2jrb3gkhs77",
    first_event_name: "Space Lady Performance at Turn! Turn! Turn!",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/01/05/4kuohkMPBT-file.jpeg?crop-x=0&crop-y=90&crop-w=1350&crop-h=1350",
    first_event_date: "2024-01-08 03:30:00",
  },
  {
    user_id: "user_2hKe0kvrchkuGaC80Omwnd6yjuI",
    username: "delladella",
    total_events_captured: "38",
    unique_event_types: "15",
    most_active_month: "October",
    favorite_type: "workshop",
    favorite_category: "arts",
    events_followed: "6",
    first_event_id: "426fh1n62qkr",
    first_event_name: "Lightmares Opening",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/07/09/4kVMCwQ37E-file.jpeg?crop-x=0&crop-y=103&crop-w=1350&crop-h=1350",
    first_event_date: "2024-07-14 00:00:00",
  },
  {
    user_id: "user_2ZFNo8HiqZN8hEjKNAsnAayoWmI",
    username: "jennybatch",
    total_events_captured: "17",
    unique_event_types: "9",
    most_active_month: "October",
    favorite_type: "workshop",
    favorite_category: "health",
    events_followed: "1",
    first_event_id: "5xpw2dgrsxcx",
    first_event_name: "Emergency Call to Action: All Out for Rafah",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/05/07/4kdX2Q2NHX-IMG_1146.jpeg?crop-x=0&crop-y=123&crop-w=1125&crop-h=1125",
    first_event_date: "2023-05-09 01:00:00",
  },
  {
    user_id: "user_2h2G0irzSWxrvUZeZW1ypBSSF9R",
    username: "thepianofarm",
    total_events_captured: "10",
    unique_event_types: "7",
    most_active_month: "December",
    favorite_type: "festival",
    favorite_category: "arts",
    events_followed: "10",
    first_event_id: "72nqtdhpgzws",
    first_event_name: "Colin Stetson with Methods Body",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/09/05/4kMcDh66Cd-file.jpeg?crop-x=0&crop-y=168&crop-w=1350&crop-h=1350",
    first_event_date: "2024-09-11 03:00:00",
  },
  {
    user_id: "user_2cN9VY11kpPmpV5UKdx3IzpdsYS",
    username: "bolyons",
    total_events_captured: "8",
    unique_event_types: "2",
    most_active_month: "November",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "0",
    first_event_id: "5348jbbwiaxk",
    first_event_name: "Urgent March and Action: Hands Off Rafah",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/02/14/4kpTnnaTEp-IMG_8845.png?crop-x=0&crop-y=438&crop-w=1125&crop-h=1125",
    first_event_date: "2024-02-15 00:30:00",
  },
  {
    user_id: "user_2eIUpewS7yNVFaYeE4WxVnl3eAV",
    username: "eggsbenedon",
    total_events_captured: "7",
    unique_event_types: "5",
    most_active_month: "November",
    favorite_type: "unknown",
    favorite_category: "community",
    events_followed: "5",
    first_event_id: "0fq1jptcdu14",
    first_event_name: "Birthday Dance Party",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/08/08/4kRJ2XD54U-file.jpeg?crop-x=0&crop-y=0&crop-w=1350&crop-h=1350",
    first_event_date: "2024-08-10 04:00:00",
  },
  {
    user_id: "user_2ZFNnktaRWUM69yaXybyunvYxnS",
    username: "jenny",
    total_events_captured: "7",
    unique_event_types: "5",
    most_active_month: "October",
    favorite_type: "movie",
    favorite_category: "entertainment",
    events_followed: "10",
    first_event_id: "82w7mtv4qxj2",
    first_event_name: "Reverb & Seduction: Deep Red with The Bavannaires",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/09/28/4kJbstLUHo-file.jpeg",
    first_event_date: "2024-09-30 03:30:00",
  },
  {
    user_id: "user_2nDoZy7RZxLGgmkKwXYMHqN8NKl",
    username: "misskinn",
    total_events_captured: "7",
    unique_event_types: "7",
    most_active_month: "October",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "8",
    first_event_id: "b2lrymtudy2f",
    first_event_name: "No Place to Grow Old",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/10/10/4kH1tnpF9t-file.jpeg",
    first_event_date: "2024-10-23 02:00:00",
  },
  {
    user_id: "user_2orS553FK0T5bBhyeqVwoTTlAoE",
    username: "fancyclubsandwich",
    total_events_captured: "7",
    unique_event_types: "5",
    most_active_month: "November",
    favorite_type: "party",
    favorite_category: "community",
    events_followed: "2",
    first_event_id: "2chlm7r7x2la",
    first_event_name: "Northwest Geology",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/19/4kBpMrUy61-file.jpeg",
    first_event_date: "2024-11-24 22:00:00",
  },
  {
    user_id: "user_2ZFNomQiHvl8GHJ4ZMFyy5qrqPp",
    username: "boogiebuffet",
    total_events_captured: "6",
    unique_event_types: "5",
    most_active_month: "July",
    favorite_type: "meeting",
    favorite_category: "community",
    events_followed: "5",
    first_event_id: "4d2gx7n02hhu",
    first_event_name: "Full Body Parentheses",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/07/08/4kVNRhDXzs-file.jpeg?crop-x=0&crop-y=787&crop-w=1350&crop-h=1350",
    first_event_date: "2024-07-13 22:00:00",
  },
  {
    user_id: "user_2pBqnOUVCqo7719ZdWRh2jCuSJA",
    username: "kaylakennett",
    total_events_captured: "6",
    unique_event_types: "5",
    most_active_month: "November",
    favorite_type: "opening",
    favorite_category: "food",
    events_followed: "5",
    first_event_id: "biadjjbqczvx",
    first_event_name: "Sushi Closet Opening",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/23/4kBDHPLmDn-file.jpeg",
    first_event_date: "2024-11-24 01:00:00",
  },
  {
    user_id: "user_2pBqnOUVCqo7719ZdWRh2jCuSJA",
    username: "kaylakennett",
    total_events_captured: "6",
    unique_event_types: "5",
    most_active_month: "November",
    favorite_type: "opening",
    favorite_category: "food",
    events_followed: "5",
    first_event_id: "d49tdjj8o55f",
    first_event_name: "Sushi Closet Opening",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/23/4kBDGqnX51-file.jpeg",
    first_event_date: "2024-11-24 01:00:00",
  },
  {
    user_id: "user_2dc1STdjoESKW87ggxXHKxd4tfA",
    username: "avowoovs",
    total_events_captured: "4",
    unique_event_types: "2",
    most_active_month: "July",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "0",
    first_event_id: "4jbwmji20djp",
    first_event_name: "Machinedrum 3FOR82_LIVE_AV",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/06/04/4kZwhf1PDQ-IMG_9975.png?crop-x=9&crop-y=636&crop-w=1232&crop-h=1232",
    first_event_date: "2024-07-11 03:00:00",
  },
  {
    user_id: "user_2ZFNocneC8tvxaIvPtn8Q92FOy2",
    username: "angela",
    total_events_captured: "4",
    unique_event_types: "2",
    most_active_month: "July",
    favorite_type: "unknown",
    favorite_category: "unknown",
    events_followed: "2",
    first_event_id: "eb8hkjt8qy4t",
    first_event_name: "Closed for Lunch",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/07/08/4kVMk8tFFu-file.jpeg?crop-x=0&crop-y=786&crop-w=1350&crop-h=1350",
    first_event_date: "2024-07-08 19:00:00",
  },
  {
    user_id: "user_2p1zliw1HaGYdtEErWLMM2EMNBa",
    username: "chrispy",
    total_events_captured: "4",
    unique_event_types: "3",
    most_active_month: "November",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "2",
    first_event_id: "17ej1kz0a20a",
    first_event_name: "2024 Winter Remix Market Vol 02",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/18/4kBtPR9FLE-file.jpeg",
    first_event_date: "2024-12-07 23:00:00",
  },
  {
    user_id: "user_2oGvww8rSiruqCrPuQvntLAHgv5",
    username: "c-sea-see",
    total_events_captured: "3",
    unique_event_types: "3",
    most_active_month: "November",
    favorite_type: "opening",
    favorite_category: "arts",
    events_followed: "1",
    first_event_id: "17ljyjwtqftw",
    first_event_name: "November First Thursday Opening",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/03/4kDqeykaAe-file.jpeg",
    first_event_date: "2024-11-08 01:00:00",
  },
  {
    user_id: "user_2hHyGCAjYA7S2P2BylRf3u1HMmL",
    username: "pigeon",
    total_events_captured: "3",
    unique_event_types: "3",
    most_active_month: "June",
    favorite_type: "workshop",
    favorite_category: "community",
    events_followed: "0",
    first_event_id: "1f64fexuzri2",
    first_event_name: "Really Really Free Market",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/06/01/4kaFpJvPKW-Screenshot_20240601-110840.png?crop-x=0&crop-y=128&crop-w=1080&crop-h=1080",
    first_event_date: "2024-06-01 19:00:00",
  },
  {
    user_id: "user_2hHyGCAjYA7S2P2BylRf3u1HMmL",
    username: "pigeon",
    total_events_captured: "3",
    unique_event_types: "3",
    most_active_month: "June",
    favorite_type: "workshop",
    favorite_category: "community",
    events_followed: "0",
    first_event_id: "e2qhkp9hvopr",
    first_event_name: "Anarchy Fun Time Crafting in the Park",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/06/01/4kaFsYLvKu-signal-2024-05-31-22-16-11-986.jpg?crop-x=83&crop-y=0&crop-w=1883&crop-h=1883",
    first_event_date: "2024-06-01 19:00:00",
  },
  {
    user_id: "user_2cbkRUTngT6c4NSgGpe5DUx5WR3",
    username: "mlreardon",
    total_events_captured: "3",
    unique_event_types: "0",
    most_active_month: null,
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: "chz2yrijaqen",
    first_event_name: "MUSIC FROM THE SOLE: I Didn't Come to Stay",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/02/27/4knjdzRr7i-PXL_20240227_224843288.jpg?crop-x=369&crop-y=1083&crop-w=2333&crop-h=2333",
    first_event_date: "2024-03-01 03:30:00",
  },
  {
    user_id: "user_2nruTkkFrotnw6R6PPxgQSTDsG9",
    username: "cozysocks",
    total_events_captured: "3",
    unique_event_types: "3",
    most_active_month: "November",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "1",
    first_event_id: "da40wlze09dz",
    first_event_name: "Rage Rejoice Resist: A Holiday Benefit Rager",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/12/06/4k9bRLp9Bh-file.jpeg",
    first_event_date: "2024-12-08 03:00:00",
  },
  {
    user_id: "user_2nVP34CTzBaz8EiEteKrhdNxoZl",
    username: "danielshinseki",
    total_events_captured: "3",
    unique_event_types: "3",
    most_active_month: "October",
    favorite_type: "party",
    favorite_category: "music",
    events_followed: "1",
    first_event_id: "9xsp34svchr1",
    first_event_name: "The Dojo",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/10/25/4kF7Ycnp2R-file.jpeg",
    first_event_date: "2024-10-27 01:00:00",
  },
  {
    user_id: "user_2ZpagQAYjGEBe7JiRlfI99Ph92y",
    username: "soonlist",
    total_events_captured: "2",
    unique_event_types: "0",
    most_active_month: null,
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: "clrg60o2o00017593900wuukr",
    first_event_name: "WORLD CITY POP Vol.23",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/01/16/4ktMCggn3K-citypop.webp?crop-x=0&crop-y=135&crop-w=640&crop-h=640",
    first_event_date: "2024-01-28 10:00:00",
  },
  {
    user_id: "user_2nGj1eQLi35jHOuhS3kkmn2sbEK",
    username: "joev",
    total_events_captured: "2",
    unique_event_types: "2",
    most_active_month: "December",
    favorite_type: "unknown",
    favorite_category: "unknown",
    events_followed: "6",
    first_event_id: "bhewuyfohalk",
    first_event_name: "Old Pal Holiday Market",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/12/07/4k9PnPdz3G-file.jpeg",
    first_event_date: "2024-12-07 18:00:00",
  },
  {
    user_id: "user_2motmGPMsvTxPinueQDElpbEI2K",
    username: "helloloom",
    total_events_captured: "2",
    unique_event_types: "2",
    most_active_month: "October",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "6",
    first_event_id: "f051maqb5zcd",
    first_event_name: "Noche de la Lucha!",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/10/22/4kFSwudV4s-file.jpeg",
    first_event_date: "2024-11-01 03:00:00",
  },
  {
    user_id: "user_2eISdi3taJdzpbPyOdijq6volhG",
    username: "snowdaysfoundation",
    total_events_captured: "2",
    unique_event_types: "1",
    most_active_month: "April",
    favorite_type: "competition",
    favorite_category: "sports",
    events_followed: "0",
    first_event_id: "5n233kw7a3ez",
    first_event_name: "CORENATION",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/03/28/4kiuJg4tCW-corenation_11x17_Timberline.png?crop-x=0&crop-y=216&crop-w=792&crop-h=792",
    first_event_date: "2024-04-06 16:00:00",
  },
  {
    user_id: "user_2cNcWaVCa7niK11DA7YHm7xMydB",
    username: "sandyriverstudio",
    total_events_captured: "2",
    unique_event_types: "1",
    most_active_month: "May",
    favorite_type: "workshop",
    favorite_category: "arts",
    events_followed: "0",
    first_event_id: "ez6p3jcq3eu1",
    first_event_name: "Valentine's Clay Date",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/02/15/4kpSXTdu9K-file.jpeg?crop-x=0&crop-y=202&crop-w=1350&crop-h=1350",
    first_event_date: "2024-02-13 08:00:00",
  },
  {
    user_id: "user_2nOge2xGJpATFera2IxKebH1wqd",
    username: "nationale",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "November",
    favorite_type: "exhibition",
    favorite_category: "arts",
    events_followed: "0",
    first_event_id: "g9shdd2k0pg8",
    first_event_name:
      "checkmate at Nationale (curated by kate shannon of chess haus)",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/27/4kAmuXSs3G-file.jpeg",
    first_event_date: "2024-12-08 01:00:00",
  },
  {
    user_id: "user_2nJmLqdRYR7lmIxDlbg0fZh1GPw",
    username: "natesoatmealcookies",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "October",
    favorite_type: "unknown",
    favorite_category: "unknown",
    events_followed: "0",
    first_event_id: "056h54lst73k",
    first_event_name: "New Hours Launch",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/10/12/4kGqHu85EK-file.jpeg",
    first_event_date: "2024-10-17 18:00:00",
  },
  {
    user_id: "user_2pJOM7M1PVEf3rkuoMVtVFRmvlr",
    username: "schaus",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "November",
    favorite_type: "movie",
    favorite_category: "entertainment",
    events_followed: "1",
    first_event_id: "2kazwzjanoug",
    first_event_name: "Into the Unknown",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/24/4kB5MRScCj-file.jpeg",
    first_event_date: "2024-12-02 03:30:00",
  },
  {
    user_id: "user_2izkP8dCDVsenu9sbPY9MptYZnA",
    username: "annelyse",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "July",
    favorite_type: "performance",
    favorite_category: "music",
    events_followed: "3",
    first_event_id: "alye6o5x6hn1",
    first_event_name: "Some Poems Before Sunset in the Trees",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/07/09/4kVKyHzn7r-file.jpeg?crop-x=0&crop-y=788&crop-w=1350&crop-h=1350",
    first_event_date: "2024-07-07 01:30:00",
  },
  {
    user_id: "user_2i3uPC0dxgHU41aBRD0fjbFg7xm",
    username: "bellelipton",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "August",
    favorite_type: "unknown",
    favorite_category: "community",
    events_followed: "0",
    first_event_id: "0djmk7u2jt03",
    first_event_name: "Yard Sale",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/08/02/4kS4rkcv6t-IMG_5171.png?crop-x=0&crop-y=656&crop-w=1125&crop-h=1125",
    first_event_date: "2024-08-03 17:00:00",
  },
  {
    user_id: "user_2dsXPiDSzuQkVg3biaFPTVMpUOm",
    username: "dineenorourke",
    total_events_captured: "1",
    unique_event_types: "0",
    most_active_month: null,
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: "0kvj5ks6siqe",
    first_event_name:
      "March Action Night: Portland City Council Candidate Meet & Greet",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/03/19/4kk5YnmSHh-Screenshot 2024-03-18 at 2.40.20 PM.png?crop-x=1&crop-y=0&crop-w=1196&crop-h=1196",
    first_event_date: "2024-03-21 01:00:00",
  },
  {
    user_id: "user_2nlSuVpOpoJuDLWR67fOEjOgSgo",
    username: "terence_online",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "November",
    favorite_type: "competition",
    favorite_category: "sports",
    events_followed: "0",
    first_event_id: "0m09k3r4a74l",
    first_event_name: "Blazers Watch Party",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/22/4kBM9H2Q7c-file.jpeg",
    first_event_date: "2024-11-28 00:00:00",
  },
];

const dataForUsersFor2024 = dataForUsersFor2024Array.reduce(
  (acc, user, index) => {
    acc[user.username] = user;
    acc[user.username].user_index = index;
    return acc;
  },
  {},
);

export default dataForUsersFor2024;
