const dataForUsersFor2024Array = [
  {
    user_id: "user_2ZFNoiajf80Q4ZiTQj8hAgatRCt",
    username: "jaronheard",
    percentile: "100.0",
    active_days: "153",
    total_events_captured: "252",
    unique_event_types: "22",
    most_active_month: "June",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "28",
  },
  {
    user_id: "user_2ZFNp40GcUNt7KKev1IYqlojZHZ",
    username: "joshcarr",
    percentile: "97.0",
    active_days: "94",
    total_events_captured: "126",
    unique_event_types: "19",
    most_active_month: "October",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "37",
  },
  {
    user_id: "user_2hKe0kvrchkuGaC80Omwnd6yjuI",
    username: "delladella",
    percentile: "93.9",
    active_days: "29",
    total_events_captured: "38",
    unique_event_types: "15",
    most_active_month: "October",
    favorite_type: "workshop",
    favorite_category: "arts",
    events_followed: "6",
  },
  {
    user_id: "user_2ZFNo8HiqZN8hEjKNAsnAayoWmI",
    username: "jennybatch",
    percentile: "90.9",
    active_days: "16",
    total_events_captured: "17",
    unique_event_types: "9",
    most_active_month: "October",
    favorite_type: "workshop",
    favorite_category: "health",
    events_followed: "1",
  },
  {
    user_id: "user_2h2G0irzSWxrvUZeZW1ypBSSF9R",
    username: "thepianofarm",
    percentile: "87.9",
    active_days: "9",
    total_events_captured: "10",
    unique_event_types: "7",
    most_active_month: "December",
    favorite_type: "festival",
    favorite_category: "arts",
    events_followed: "10",
  },
  {
    user_id: "user_2cN9VY11kpPmpV5UKdx3IzpdsYS",
    username: "bolyons",
    percentile: "84.8",
    active_days: "8",
    total_events_captured: "8",
    unique_event_types: "2",
    most_active_month: "November",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "0",
  },
  {
    user_id: "user_2eIUpewS7yNVFaYeE4WxVnl3eAV",
    username: "eggsbenedon",
    percentile: "81.8",
    active_days: "7",
    total_events_captured: "7",
    unique_event_types: "5",
    most_active_month: "November",
    favorite_type: "unknown",
    favorite_category: "community",
    events_followed: "5",
  },
  {
    user_id: "user_2ZFNnktaRWUM69yaXybyunvYxnS",
    username: "jenny",
    percentile: "81.8",
    active_days: "6",
    total_events_captured: "7",
    unique_event_types: "5",
    most_active_month: "October",
    favorite_type: "movie",
    favorite_category: "entertainment",
    events_followed: "10",
  },
  {
    user_id: "user_2nDoZy7RZxLGgmkKwXYMHqN8NKl",
    username: "misskinn",
    percentile: "81.8",
    active_days: "6",
    total_events_captured: "7",
    unique_event_types: "7",
    most_active_month: "October",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "8",
  },
  {
    user_id: "user_2orS553FK0T5bBhyeqVwoTTlAoE",
    username: "fancyclubsandwich",
    percentile: "81.8",
    active_days: "6",
    total_events_captured: "7",
    unique_event_types: "5",
    most_active_month: "November",
    favorite_type: "party",
    favorite_category: "community",
    events_followed: "2",
  },
  {
    user_id: "user_2ZFNomQiHvl8GHJ4ZMFyy5qrqPp",
    username: "boogiebuffet",
    percentile: "69.7",
    active_days: "5",
    total_events_captured: "6",
    unique_event_types: "5",
    most_active_month: "July",
    favorite_type: "meeting",
    favorite_category: "community",
    events_followed: "5",
  },
  {
    user_id: "user_2pBqnOUVCqo7719ZdWRh2jCuSJA",
    username: "kaylakennett",
    percentile: "69.7",
    active_days: "3",
    total_events_captured: "6",
    unique_event_types: "5",
    most_active_month: "November",
    favorite_type: "opening",
    favorite_category: "food",
    events_followed: "5",
  },
  {
    user_id: "user_2dc1STdjoESKW87ggxXHKxd4tfA",
    username: "avowoovs",
    percentile: "63.6",
    active_days: "4",
    total_events_captured: "4",
    unique_event_types: "2",
    most_active_month: "July",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "0",
  },
  {
    user_id: "user_2ZFNocneC8tvxaIvPtn8Q92FOy2",
    username: "angela",
    percentile: "63.6",
    active_days: "4",
    total_events_captured: "4",
    unique_event_types: "2",
    most_active_month: "July",
    favorite_type: "unknown",
    favorite_category: "unknown",
    events_followed: "2",
  },
  {
    user_id: "user_2p1zliw1HaGYdtEErWLMM2EMNBa",
    username: "chrispy",
    percentile: "63.6",
    active_days: "2",
    total_events_captured: "4",
    unique_event_types: "3",
    most_active_month: "November",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "2",
  },
  {
    user_id: "user_2oGvww8rSiruqCrPuQvntLAHgv5",
    username: "c-sea-see",
    percentile: "54.5",
    active_days: "2",
    total_events_captured: "3",
    unique_event_types: "3",
    most_active_month: "November",
    favorite_type: "opening",
    favorite_category: "arts",
    events_followed: "1",
  },
  {
    user_id: "user_2hHyGCAjYA7S2P2BylRf3u1HMmL",
    username: "pigeon",
    percentile: "54.5",
    active_days: "1",
    total_events_captured: "3",
    unique_event_types: "3",
    most_active_month: "June",
    favorite_type: "workshop",
    favorite_category: "community",
    events_followed: "0",
  },
  {
    user_id: "user_2cbkRUTngT6c4NSgGpe5DUx5WR3",
    username: "mlreardon",
    percentile: "54.5",
    active_days: "3",
    total_events_captured: "3",
    unique_event_types: "0",
    most_active_month: null,
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
  },
  {
    user_id: "user_2nruTkkFrotnw6R6PPxgQSTDsG9",
    username: "cozysocks",
    percentile: "54.5",
    active_days: "2",
    total_events_captured: "3",
    unique_event_types: "3",
    most_active_month: "November",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "1",
  },
  {
    user_id: "user_2nVP34CTzBaz8EiEteKrhdNxoZl",
    username: "danielshinseki",
    percentile: "54.5",
    active_days: "3",
    total_events_captured: "3",
    unique_event_types: "3",
    most_active_month: "October",
    favorite_type: "party",
    favorite_category: "music",
    events_followed: "1",
  },
  {
    user_id: "user_2ZpagQAYjGEBe7JiRlfI99Ph92y",
    username: "soonlist",
    percentile: "39.4",
    active_days: "2",
    total_events_captured: "2",
    unique_event_types: "0",
    most_active_month: null,
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
  },
  {
    user_id: "user_2nGj1eQLi35jHOuhS3kkmn2sbEK",
    username: "joev",
    percentile: "39.4",
    active_days: "2",
    total_events_captured: "2",
    unique_event_types: "2",
    most_active_month: "December",
    favorite_type: "unknown",
    favorite_category: "unknown",
    events_followed: "6",
  },
  {
    user_id: "user_2motmGPMsvTxPinueQDElpbEI2K",
    username: "helloloom",
    percentile: "39.4",
    active_days: "2",
    total_events_captured: "2",
    unique_event_types: "2",
    most_active_month: "October",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "6",
  },
  {
    user_id: "user_2eISdi3taJdzpbPyOdijq6volhG",
    username: "snowdaysfoundation",
    percentile: "39.4",
    active_days: "2",
    total_events_captured: "2",
    unique_event_types: "1",
    most_active_month: "April",
    favorite_type: "competition",
    favorite_category: "sports",
    events_followed: "0",
  },
  {
    user_id: "user_2cNcWaVCa7niK11DA7YHm7xMydB",
    username: "sandyriverstudio",
    percentile: "39.4",
    active_days: "2",
    total_events_captured: "2",
    unique_event_types: "1",
    most_active_month: "May",
    favorite_type: "workshop",
    favorite_category: "arts",
    events_followed: "0",
  },
  {
    user_id: "user_2nOge2xGJpATFera2IxKebH1wqd",
    username: "nationale",
    percentile: "24.2",
    active_days: "1",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "November",
    favorite_type: "exhibition",
    favorite_category: "arts",
    events_followed: "0",
  },
  {
    user_id: "user_2nJmLqdRYR7lmIxDlbg0fZh1GPw",
    username: "natesoatmealcookies",
    percentile: "24.2",
    active_days: "1",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "October",
    favorite_type: "unknown",
    favorite_category: "unknown",
    events_followed: "0",
  },
  {
    user_id: "user_2pJOM7M1PVEf3rkuoMVtVFRmvlr",
    username: "schaus",
    percentile: "24.2",
    active_days: "1",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "November",
    favorite_type: "movie",
    favorite_category: "entertainment",
    events_followed: "1",
  },
  {
    user_id: "user_2izkP8dCDVsenu9sbPY9MptYZnA",
    username: "annelyse",
    percentile: "24.2",
    active_days: "1",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "July",
    favorite_type: "performance",
    favorite_category: "music",
    events_followed: "3",
  },
  {
    user_id: "user_2i3uPC0dxgHU41aBRD0fjbFg7xm",
    username: "bellelipton",
    percentile: "24.2",
    active_days: "1",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "August",
    favorite_type: "unknown",
    favorite_category: "community",
    events_followed: "0",
  },
  {
    user_id: "user_2dsXPiDSzuQkVg3biaFPTVMpUOm",
    username: "dineenorourke",
    percentile: "24.2",
    active_days: "1",
    total_events_captured: "1",
    unique_event_types: "0",
    most_active_month: null,
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
  },
  {
    user_id: "user_2nlSuVpOpoJuDLWR67fOEjOgSgo",
    username: "terence_online",
    percentile: "24.2",
    active_days: "1",
    total_events_captured: "1",
    unique_event_types: "1",
    most_active_month: "November",
    favorite_type: "competition",
    favorite_category: "sports",
    events_followed: "0",
  },
];

const dataForUsersFor2024 = dataForUsersFor2024Array.reduce((acc, user) => {
  acc[user.username] = user;
  return acc;
}, {});

export default dataForUsersFor2024;
