// First define the interface for a single user's data
export interface UserData2024 {
  user_id: string;
  username: string;
  emoji: string | null;
  created_at: string;
  total_events_captured: string;
  unique_event_types: string;
  favorite_type: string | null;
  favorite_category: string | null;
  events_followed: string;
  first_event_id: string | null;
  first_event_name: string | null;
  first_event_image: string | null;
  first_event_date: string | null;
  user_index?: number;
}

// Define the shape of the final data structure using Record type
type UsersData2024 = Record<string, UserData2024>;

const dataForUsersFor2024Array = [
  {
    user_id: "user_2ZFNoiajf80Q4ZiTQj8hAgatRCt",
    username: "jaronheard",
    emoji: "💖",
    created_at: "2023-11-04 01:58:14",
    total_events_captured: "252",
    unique_event_types: "22",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "28",
    first_event_id: "clrbwg21u0001f48lm6x2zsoq",
    first_event_name: "Dig A Hole Zines Fundraising PARTY",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/01/13/4ktjNP7rKz-file.jpeg?crop-x=0&crop-y=87&crop-w=1350&crop-h=1350",
    first_event_date: "2024-01-13 06:00:00",
  },
  {
    user_id: "user_2ZFNp40GcUNt7KKev1IYqlojZHZ",
    username: "joshcarr",
    emoji: "🙏",
    created_at: "2023-11-04 01:58:15",
    total_events_captured: "126",
    unique_event_types: "19",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "37",
    first_event_id: "clr08f7um0001u2jrb3gkhs77",
    first_event_name: "Space Lady Performance at Turn! Turn! Turn!",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/01/05/4kuohkMPBT-file.jpeg?crop-x=0&crop-y=90&crop-w=1350&crop-h=1350",
    first_event_date: "2024-01-08 03:30:00",
  },
  {
    user_id: "user_2hKe0kvrchkuGaC80Omwnd6yjuI",
    username: "delladella",
    emoji: "🌀",
    created_at: "2024-06-02 16:49:35",
    total_events_captured: "38",
    unique_event_types: "15",
    favorite_type: "workshop",
    favorite_category: "arts",
    events_followed: "6",
    first_event_id: "426fh1n62qkr",
    first_event_name: "Lightmares Opening",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/07/09/4kVMCwQ37E-file.jpeg?crop-x=0&crop-y=103&crop-w=1350&crop-h=1350",
    first_event_date: "2024-07-14 00:00:00",
  },
  {
    user_id: "user_2ZFNo8HiqZN8hEjKNAsnAayoWmI",
    username: "jennybatch",
    emoji: "🎈",
    created_at: "2023-11-04 01:58:13",
    total_events_captured: "17",
    unique_event_types: "9",
    favorite_type: "workshop",
    favorite_category: "health",
    events_followed: "1",
    first_event_id: "5xpw2dgrsxcx",
    first_event_name: "Emergency Call to Action: All Out for Rafah",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/05/07/4kdX2Q2NHX-IMG_1146.jpeg?crop-x=0&crop-y=123&crop-w=1125&crop-h=1125",
    first_event_date: "2023-05-09 01:00:00",
  },
  {
    user_id: "user_2h2G0irzSWxrvUZeZW1ypBSSF9R",
    username: "thepianofarm",
    emoji: "🚣🏽",
    created_at: "2024-05-27 04:35:39",
    total_events_captured: "10",
    unique_event_types: "7",
    favorite_type: "festival",
    favorite_category: "arts",
    events_followed: "10",
    first_event_id: "72nqtdhpgzws",
    first_event_name: "Colin Stetson with Methods Body",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/09/05/4kMcDh66Cd-file.jpeg?crop-x=0&crop-y=168&crop-w=1350&crop-h=1350",
    first_event_date: "2024-09-11 03:00:00",
  },
  {
    user_id: "user_2cN9VY11kpPmpV5UKdx3IzpdsYS",
    username: "bolyons",
    emoji: "🤙",
    created_at: "2024-02-14 20:06:36",
    total_events_captured: "8",
    unique_event_types: "2",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "0",
    first_event_id: "5348jbbwiaxk",
    first_event_name: "Urgent March and Action: Hands Off Rafah",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/02/14/4kpTnnaTEp-IMG_8845.png?crop-x=0&crop-y=438&crop-w=1125&crop-h=1125",
    first_event_date: "2024-02-15 00:30:00",
  },
  {
    user_id: "user_2ZFNnktaRWUM69yaXybyunvYxnS",
    username: "jenny",
    emoji: "🌚",
    created_at: "2023-11-08 00:05:19",
    total_events_captured: "7",
    unique_event_types: "5",
    favorite_type: "movie",
    favorite_category: "entertainment",
    events_followed: "10",
    first_event_id: "82w7mtv4qxj2",
    first_event_name: "Reverb & Seduction: Deep Red with The Bavannaires",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/09/28/4kJbstLUHo-file.jpeg",
    first_event_date: "2024-09-30 03:30:00",
  },
  {
    user_id: "user_2nDoZy7RZxLGgmkKwXYMHqN8NKl",
    username: "misskinn",
    emoji: "🍿",
    created_at: "2024-10-09 23:37:48",
    total_events_captured: "7",
    unique_event_types: "7",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "8",
    first_event_id: "b2lrymtudy2f",
    first_event_name: "No Place to Grow Old",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/10/10/4kH1tnpF9t-file.jpeg",
    first_event_date: "2024-10-23 02:00:00",
  },
  {
    user_id: "user_2eIUpewS7yNVFaYeE4WxVnl3eAV",
    username: "eggsbenedon",
    emoji: "🤸",
    created_at: "2024-03-28 02:09:30",
    total_events_captured: "7",
    unique_event_types: "5",
    favorite_type: "unknown",
    favorite_category: "community",
    events_followed: "5",
    first_event_id: "0fq1jptcdu14",
    first_event_name: "Birthday Dance Party",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/08/08/4kRJ2XD54U-file.jpeg?crop-x=0&crop-y=0&crop-w=1350&crop-h=1350",
    first_event_date: "2024-08-10 04:00:00",
  },
  {
    user_id: "user_2orS553FK0T5bBhyeqVwoTTlAoE",
    username: "fancyclubsandwich",
    emoji: null,
    created_at: "2024-11-14 23:13:36",
    total_events_captured: "7",
    unique_event_types: "5",
    favorite_type: "party",
    favorite_category: "community",
    events_followed: "2",
    first_event_id: "2chlm7r7x2la",
    first_event_name: "Northwest Geology",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/19/4kBpMrUy61-file.jpeg",
    first_event_date: "2024-11-24 22:00:00",
  },
  {
    user_id: "user_2pBqnOUVCqo7719ZdWRh2jCuSJA",
    username: "kaylakennett",
    emoji: "💐",
    created_at: "2024-11-22 04:33:04",
    total_events_captured: "6",
    unique_event_types: "5",
    favorite_type: "opening",
    favorite_category: "food",
    events_followed: "5",
    first_event_id: "d49tdjj8o55f",
    first_event_name: "Sushi Closet Opening",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/23/4kBDGqnX51-file.jpeg",
    first_event_date: "2024-11-24 01:00:00",
  },
  {
    user_id: "user_2ZFNomQiHvl8GHJ4ZMFyy5qrqPp",
    username: "boogiebuffet",
    emoji: "😎",
    created_at: "2023-11-04 01:58:14",
    total_events_captured: "6",
    unique_event_types: "5",
    favorite_type: "meeting",
    favorite_category: "community",
    events_followed: "5",
    first_event_id: "4d2gx7n02hhu",
    first_event_name: "Full Body Parentheses",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/07/08/4kVNRhDXzs-file.jpeg?crop-x=0&crop-y=787&crop-w=1350&crop-h=1350",
    first_event_date: "2024-07-13 22:00:00",
  },
  {
    user_id: "user_2p1zliw1HaGYdtEErWLMM2EMNBa",
    username: "chrispy",
    emoji: null,
    created_at: "2024-11-18 16:48:43",
    total_events_captured: "4",
    unique_event_types: "3",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "2",
    first_event_id: "17ej1kz0a20a",
    first_event_name: "2024 Winter Remix Market Vol 02",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/18/4kBtPR9FLE-file.jpeg",
    first_event_date: "2024-12-07 23:00:00",
  },
  {
    user_id: "user_2ZFNocneC8tvxaIvPtn8Q92FOy2",
    username: "angela",
    emoji: "🧩",
    created_at: "2023-11-04 01:58:14",
    total_events_captured: "4",
    unique_event_types: "2",
    favorite_type: "unknown",
    favorite_category: "unknown",
    events_followed: "2",
    first_event_id: "eb8hkjt8qy4t",
    first_event_name: "Closed for Lunch",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/07/08/4kVMk8tFFu-file.jpeg?crop-x=0&crop-y=786&crop-w=1350&crop-h=1350",
    first_event_date: "2024-07-08 19:00:00",
  },
  {
    user_id: "user_2dc1STdjoESKW87ggxXHKxd4tfA",
    username: "avowoovs",
    emoji: null,
    created_at: "2024-03-13 01:15:54",
    total_events_captured: "4",
    unique_event_types: "2",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "0",
    first_event_id: "4jbwmji20djp",
    first_event_name: "Machinedrum 3FOR82_LIVE_AV",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/06/04/4kZwhf1PDQ-IMG_9975.png?crop-x=9&crop-y=636&crop-w=1232&crop-h=1232",
    first_event_date: "2024-07-11 03:00:00",
  },
  {
    user_id: "user_2oGvww8rSiruqCrPuQvntLAHgv5",
    username: "c-sea-see",
    emoji: "🐯",
    created_at: "2024-11-02 00:56:10",
    total_events_captured: "3",
    unique_event_types: "3",
    favorite_type: "opening",
    favorite_category: "arts",
    events_followed: "1",
    first_event_id: "17ljyjwtqftw",
    first_event_name: "November First Thursday Opening",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/03/4kDqeykaAe-file.jpeg",
    first_event_date: "2024-11-08 01:00:00",
  },
  {
    user_id: "user_2nruTkkFrotnw6R6PPxgQSTDsG9",
    username: "cozysocks",
    emoji: "🧦",
    created_at: "2024-10-24 04:18:46",
    total_events_captured: "3",
    unique_event_types: "3",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "1",
    first_event_id: "da40wlze09dz",
    first_event_name: "Rage Rejoice Resist: A Holiday Benefit Rager",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/12/06/4k9bRLp9Bh-file.jpeg",
    first_event_date: "2024-12-08 03:00:00",
  },
  {
    user_id: "user_2nVP34CTzBaz8EiEteKrhdNxoZl",
    username: "danielshinseki",
    emoji: "🐢",
    created_at: "2024-10-16 05:04:27",
    total_events_captured: "3",
    unique_event_types: "3",
    favorite_type: "party",
    favorite_category: "music",
    events_followed: "1",
    first_event_id: "9xsp34svchr1",
    first_event_name: "The Dojo",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/10/25/4kF7Ycnp2R-file.jpeg",
    first_event_date: "2024-10-27 01:00:00",
  },
  {
    user_id: "user_2hHyGCAjYA7S2P2BylRf3u1HMmL",
    username: "pigeon",
    emoji: null,
    created_at: "2024-06-01 18:06:41",
    total_events_captured: "3",
    unique_event_types: "3",
    favorite_type: "workshop",
    favorite_category: "community",
    events_followed: "0",
    first_event_id: "1f64fexuzri2",
    first_event_name: "Really Really Free Market",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/06/01/4kaFpJvPKW-Screenshot_20240601-110840.png?crop-x=0&crop-y=128&crop-w=1080&crop-h=1080",
    first_event_date: "2024-06-01 19:00:00",
  },
  {
    user_id: "user_2hHyGCAjYA7S2P2BylRf3u1HMmL",
    username: "pigeon",
    emoji: null,
    created_at: "2024-06-01 18:06:41",
    total_events_captured: "3",
    unique_event_types: "3",
    favorite_type: "workshop",
    favorite_category: "community",
    events_followed: "0",
    first_event_id: "e2qhkp9hvopr",
    first_event_name: "Anarchy Fun Time Crafting in the Park",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/06/01/4kaFsYLvKu-signal-2024-05-31-22-16-11-986.jpg?crop-x=83&crop-y=0&crop-w=1883&crop-h=1883",
    first_event_date: "2024-06-01 19:00:00",
  },
  {
    user_id: "user_2cbkRUTngT6c4NSgGpe5DUx5WR3",
    username: "mlreardon",
    emoji: null,
    created_at: "2024-02-20 00:07:40",
    total_events_captured: "3",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: "chz2yrijaqen",
    first_event_name: "MUSIC FROM THE SOLE: I Didn't Come to Stay",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/02/27/4knjdzRr7i-PXL_20240227_224843288.jpg?crop-x=369&crop-y=1083&crop-w=2333&crop-h=2333",
    first_event_date: "2024-03-01 03:30:00",
  },
  {
    user_id: "user_2nGj1eQLi35jHOuhS3kkmn2sbEK",
    username: "joev",
    emoji: "👻",
    created_at: "2024-10-11 00:21:34",
    total_events_captured: "2",
    unique_event_types: "2",
    favorite_type: "unknown",
    favorite_category: "unknown",
    events_followed: "6",
    first_event_id: "bhewuyfohalk",
    first_event_name: "Old Pal Holiday Market",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/12/07/4k9PnPdz3G-file.jpeg",
    first_event_date: "2024-12-07 18:00:00",
  },
  {
    user_id: "user_2motmGPMsvTxPinueQDElpbEI2K",
    username: "helloloom",
    emoji: "🪐",
    created_at: "2024-10-01 03:55:14",
    total_events_captured: "2",
    unique_event_types: "2",
    favorite_type: "concert",
    favorite_category: "music",
    events_followed: "6",
    first_event_id: "f051maqb5zcd",
    first_event_name: "Noche de la Lucha!",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/10/22/4kFSwudV4s-file.jpeg",
    first_event_date: "2024-11-01 03:00:00",
  },
  {
    user_id: "user_2eISdi3taJdzpbPyOdijq6volhG",
    username: "snowdaysfoundation",
    emoji: null,
    created_at: "2024-03-28 01:51:28",
    total_events_captured: "2",
    unique_event_types: "1",
    favorite_type: "competition",
    favorite_category: "sports",
    events_followed: "0",
    first_event_id: "5n233kw7a3ez",
    first_event_name: "CORENATION",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/03/28/4kiuJg4tCW-corenation_11x17_Timberline.png?crop-x=0&crop-y=216&crop-w=792&crop-h=792",
    first_event_date: "2024-04-06 16:00:00",
  },
  {
    user_id: "user_2cNcWaVCa7niK11DA7YHm7xMydB",
    username: "sandyriverstudio",
    emoji: null,
    created_at: "2024-02-15 00:05:09",
    total_events_captured: "2",
    unique_event_types: "1",
    favorite_type: "workshop",
    favorite_category: "arts",
    events_followed: "0",
    first_event_id: "ez6p3jcq3eu1",
    first_event_name: "Valentine's Clay Date",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/02/15/4kpSXTdu9K-file.jpeg?crop-x=0&crop-y=202&crop-w=1350&crop-h=1350",
    first_event_date: "2024-02-13 08:00:00",
  },
  {
    user_id: "user_2ZpagQAYjGEBe7JiRlfI99Ph92y",
    username: "soonlist",
    emoji: "🔜",
    created_at: "2023-12-21 01:19:46",
    total_events_captured: "2",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: "clrg60o2o00017593900wuukr",
    first_event_name: "WORLD CITY POP Vol.23",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/01/16/4ktMCggn3K-citypop.webp?crop-x=0&crop-y=135&crop-w=640&crop-h=640",
    first_event_date: "2024-01-28 10:00:00",
  },
  {
    user_id: "user_2izkP8dCDVsenu9sbPY9MptYZnA",
    username: "annelyse",
    emoji: null,
    created_at: "2024-07-09 04:52:47",
    total_events_captured: "1",
    unique_event_types: "1",
    favorite_type: "performance",
    favorite_category: "music",
    events_followed: "3",
    first_event_id: "alye6o5x6hn1",
    first_event_name: "Some Poems Before Sunset in the Trees",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/07/09/4kVKyHzn7r-file.jpeg?crop-x=0&crop-y=788&crop-w=1350&crop-h=1350",
    first_event_date: "2024-07-07 01:30:00",
  },
  {
    user_id: "user_2pJOM7M1PVEf3rkuoMVtVFRmvlr",
    username: "schaus",
    emoji: null,
    created_at: "2024-11-24 20:37:42",
    total_events_captured: "1",
    unique_event_types: "1",
    favorite_type: "movie",
    favorite_category: "entertainment",
    events_followed: "1",
    first_event_id: "2kazwzjanoug",
    first_event_name: "Into the Unknown",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/24/4kB5MRScCj-file.jpeg",
    first_event_date: "2024-12-02 03:30:00",
  },
  {
    user_id: "user_2nlSuVpOpoJuDLWR67fOEjOgSgo",
    username: "terence_online",
    emoji: "👹",
    created_at: "2024-10-21 21:33:14",
    total_events_captured: "1",
    unique_event_types: "1",
    favorite_type: "competition",
    favorite_category: "sports",
    events_followed: "0",
    first_event_id: "0m09k3r4a74l",
    first_event_name: "Blazers Watch Party",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/22/4kBM9H2Q7c-file.jpeg",
    first_event_date: "2024-11-28 00:00:00",
  },
  {
    user_id: "user_2nOge2xGJpATFera2IxKebH1wqd",
    username: "nationale",
    emoji: "✨",
    created_at: "2024-10-13 20:00:29",
    total_events_captured: "1",
    unique_event_types: "1",
    favorite_type: "exhibition",
    favorite_category: "arts",
    events_followed: "0",
    first_event_id: "g9shdd2k0pg8",
    first_event_name:
      "checkmate at Nationale (curated by kate shannon of chess haus)",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/11/27/4kAmuXSs3G-file.jpeg",
    first_event_date: "2024-12-08 01:00:00",
  },
  {
    user_id: "user_2nJmLqdRYR7lmIxDlbg0fZh1GPw",
    username: "natesoatmealcookies",
    emoji: "🍪",
    created_at: "2024-10-12 02:18:21",
    total_events_captured: "1",
    unique_event_types: "1",
    favorite_type: "unknown",
    favorite_category: "unknown",
    events_followed: "0",
    first_event_id: "056h54lst73k",
    first_event_name: "New Hours Launch",
    first_event_image:
      "https://upcdn.io/12a1yek/raw/uploads/2024/10/12/4kGqHu85EK-file.jpeg",
    first_event_date: "2024-10-17 18:00:00",
  },
  {
    user_id: "user_2i3uPC0dxgHU41aBRD0fjbFg7xm",
    username: "bellelipton",
    emoji: null,
    created_at: "2024-06-18 17:25:56",
    total_events_captured: "1",
    unique_event_types: "1",
    favorite_type: "unknown",
    favorite_category: "community",
    events_followed: "0",
    first_event_id: "0djmk7u2jt03",
    first_event_name: "Yard Sale",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/08/02/4kS4rkcv6t-IMG_5171.png?crop-x=0&crop-y=656&crop-w=1125&crop-h=1125",
    first_event_date: "2024-08-03 17:00:00",
  },
  {
    user_id: "user_2dsXPiDSzuQkVg3biaFPTVMpUOm",
    username: "dineenorourke",
    emoji: null,
    created_at: "2024-03-18 21:35:39",
    total_events_captured: "1",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: "0kvj5ks6siqe",
    first_event_name:
      "March Action Night: Portland City Council Candidate Meet & Greet",
    first_event_image:
      "https://upcdn.io/12a1yek/image/uploads/2024/03/19/4kk5YnmSHh-Screenshot 2024-03-18 at 2.40.20 PM.png?crop-x=1&crop-y=0&crop-w=1196&crop-h=1196",
    first_event_date: "2024-03-21 01:00:00",
  },
  {
    user_id: "user_2oHAal6B4SN7HcW2pJEqO6XgHcV",
    username: "erbrowne",
    emoji: "🧜",
    created_at: "2024-11-02 02:56:32",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "14",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2oAuwBZMKyxgI2Ih0LVYoVsHF2I",
    username: "donocado",
    emoji: "🥑",
    created_at: "2024-10-30 21:48:59",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "1",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2liqj7DcVb3CU5dEmhwZRRTwdbU",
    username: "not-quite-occasionally",
    emoji: "🪰",
    created_at: "2024-09-07 01:42:57",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "1",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2ZFNndMSE0gtoMsCbeLfsv84DXi",
    username: "ginabobina",
    emoji: "🌋",
    created_at: "2023-11-11 02:07:41",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "1",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2pLYQci9OMzXrQwZxmhKXwsVT5Z",
    username: "brynnemarie",
    emoji: "🦋",
    created_at: "2024-11-25 15:00:08",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2oRBPZgVGcuya44Nwtl9Mk3bhWL",
    username: "marissairish",
    emoji: "🐞",
    created_at: "2024-11-05 16:01:27",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2o7rMTSeo5xUqx7ka2z4xiDG84Y",
    username: "devvvvv",
    emoji: null,
    created_at: "2024-10-29 19:50:07",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2nr5njlzwwi5AouvhahgaxX1XwT",
    username: "marcello",
    emoji: "🤌",
    created_at: "2024-10-23 21:22:02",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2nqfV4ivsbeaPIYk1UX3zVUIjJO",
    username: "sheldonnevarez",
    emoji: "🥜",
    created_at: "2024-10-23 17:45:48",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2nE84NRGvWCqtrh8lvMDKD92Ky1",
    username: "trombs",
    emoji: null,
    created_at: "2024-10-10 02:18:05",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2mUU5rTCsOSrc1jiytfEwdYKnRc",
    username: "carly",
    emoji: null,
    created_at: "2024-09-23 22:27:49",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2lyosfu5AnlQ3i3FUyn5OQkZ2sp",
    username: "goldrat",
    emoji: null,
    created_at: "2024-09-12 17:24:45",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2i9QtTQ1E6TLU2XOmgVg3ErdvX6",
    username: "houseofsalvage",
    emoji: null,
    created_at: "2024-06-20 16:22:09",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2hw7eZQes82SmeBJupSsQzkq48Q",
    username: "sarahsojourner",
    emoji: null,
    created_at: "2024-06-15 23:16:22",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2ht5hMjVMSZTHsJU8AvCFkS7TeY",
    username: "makingearthcool",
    emoji: null,
    created_at: "2024-06-14 21:30:50",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2hh9slMlQWRbtgNU1i36zgIDuU4",
    username: "turoczy",
    emoji: null,
    created_at: "2024-06-10 16:07:32",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2hHZjsf9in0BrNzHhcIWpjgaeJk",
    username: "slevy",
    emoji: null,
    created_at: "2024-06-01 14:45:02",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2hFHZqXTaKFD4P7dhxmLX9wacKn",
    username: "emma",
    emoji: null,
    created_at: "2024-05-31 19:16:05",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2gTSiGzQRtgWWp6cZAY8BIfexJN",
    username: "jaronheard20240514",
    emoji: null,
    created_at: "2024-05-14 20:56:41",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2gQXLTJLQ3RvLDmotSCkRhgQJFY",
    username: "jaronheard202405131",
    emoji: null,
    created_at: "2024-05-13 20:05:20",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2gLKSaWH0KwuifV4ZBwbG2k10f6",
    username: "jaronheard20240511",
    emoji: null,
    created_at: "2024-05-11 23:50:19",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2djkNOAnAg3upkUf1OpmVtUiMOB",
    username: "jaronheard031524",
    emoji: null,
    created_at: "2024-03-15 18:53:57",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2dhgZo7fYARcMi0dkaxxbaDHG1x",
    username: "jaronheard031424",
    emoji: null,
    created_at: "2024-03-15 01:23:04",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2dh5cM6b88zq2hH3NEXPlfDu140",
    username: "postpostcard",
    emoji: null,
    created_at: "2024-03-14 20:19:09",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2dBySwZ1myQIeehMCs4sQIV2YVK",
    username: "brunowego",
    emoji: null,
    created_at: "2024-03-03 19:56:12",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2cMusXfGJaEbZHsWYSITyGaTAN5",
    username: "meganmckissack",
    emoji: null,
    created_at: "2024-02-14 18:06:17",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2c7Q6XyZBj0TMZDCPWJdLnbkRqQ",
    username: "midorihirose",
    emoji: null,
    created_at: "2024-02-09 06:26:04",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2b1mt8U1jMULPDaVRSaQYWvCLUk",
    username: "porpoisestudio",
    emoji: null,
    created_at: "2024-01-16 07:46:14",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2ZpL8YqwBolvjQkpxszZ1QyPITD",
    username: "selena",
    emoji: null,
    created_at: "2023-12-20 23:12:00",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2ZFNnCjUeStRyUq307FZMjJjuY8",
    username: "steben3x",
    emoji: null,
    created_at: "2023-12-03 02:05:25",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2ZFNnMxrJfrchz5Xl24LhqC6XgI",
    username: "bg2323",
    emoji: null,
    created_at: "2023-11-28 21:25:45",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2ZFNnRXtBIYswbvU2ULLBzAQr4D",
    username: "sarah-a",
    emoji: null,
    created_at: "2023-11-17 20:40:44",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2ZFNpEb1n0KfBTkcqdyc5oFfIQ0",
    username: "schoolofartandtime",
    emoji: "⏳",
    created_at: "2023-11-04 01:58:15",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2ZFNoKguMDBlBDM5FqSgvPeG2lN",
    username: "skeske",
    emoji: null,
    created_at: "2023-11-04 01:58:14",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
  {
    user_id: "user_2ZFNnzrtcDkub6oAqxULhCS9mbU",
    username: "plnt_dd",
    emoji: null,
    created_at: "2023-11-04 01:58:13",
    total_events_captured: "0",
    unique_event_types: "0",
    favorite_type: null,
    favorite_category: null,
    events_followed: "0",
    first_event_id: null,
    first_event_name: null,
    first_event_image: null,
    first_event_date: null,
  },
];

const dataForUsersFor2024 = dataForUsersFor2024Array.reduce<UsersData2024>(
  (acc, user, index) => {
    acc[user.username] = {
      ...user,
      user_index: index,
    };
    return acc;
  },
  {},
);

export default dataForUsersFor2024;
