import React from "react";
import {
  Calendar,
  Crown,
  Heart,
  Sparkles,
  Star,
  Trophy,
  Users,
} from "lucide-react";

import dataForUsersFor2024 from "./dataForUsersFor2024";

const YearInReviewCard = ({
  user_id,
  username,
  percentile,
  active_days,
  total_events_captured,
  unique_event_types,
  most_active_month,
  favorite_type,
  favorite_category,
  events_followed,
}) => {
  // Convert string values to numbers and calculate top percentile
  const topPercentile = Math.round(100 - parseFloat(percentile));

  return (
    <div className="mx-auto max-w-2xl rounded-xl bg-gradient-to-br from-purple-600 to-blue-600 p-8 text-white shadow-xl">
      <div className="space-y-6">
        {/* Header */}
        <div className="space-y-2 text-center">
          <div className="flex items-center justify-center gap-2">
            <Sparkles className="h-6 w-6" />
            <h1 className="text-3xl font-bold">2024 Year in Review</h1>
            <Sparkles className="h-6 w-6" />
          </div>
          <p className="text-xl font-medium">@{username}</p>
        </div>

        {/* Capturer Status */}
        <div className="rounded-lg bg-white/10 p-6 backdrop-blur-sm">
          <div className="mb-4 flex items-center gap-2">
            <Crown className="h-6 w-6 text-yellow-300" />
            <h2 className="text-2xl font-bold">
              Top {topPercentile}% Capturer!
            </h2>
          </div>
          <p className="text-lg">
            You're in the top{" "}
            <span className="font-bold text-yellow-300">{topPercentile}%</span>{" "}
            of all capturers this year
          </p>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-2 gap-4">
          <div className="rounded-lg bg-white/10 p-4 backdrop-blur-sm">
            <div className="mb-2 flex items-center gap-2">
              <Calendar className="h-5 w-5" />
              <h3 className="font-semibold">Events Captured</h3>
            </div>
            <p className="text-3xl font-bold">
              {parseInt(total_events_captured).toLocaleString()}
            </p>
          </div>

          <div className="rounded-lg bg-white/10 p-4 backdrop-blur-sm">
            <div className="mb-2 flex items-center gap-2">
              <Users className="h-5 w-5" />
              <h3 className="font-semibold">Active Days</h3>
            </div>
            <p className="text-3xl font-bold">
              {parseInt(active_days).toLocaleString()}
            </p>
          </div>
        </div>

        {/* Preferences */}
        <div className="space-y-4 rounded-lg bg-white/10 p-6 backdrop-blur-sm">
          <div>
            <div className="mb-2 flex items-center gap-2">
              <Star className="h-5 w-5 text-yellow-300" />
              <h3 className="font-semibold">Your Go-To Event Type</h3>
            </div>
            <p className="text-2xl font-bold capitalize">{favorite_type}</p>
          </div>

          <div>
            <div className="mb-2 flex items-center gap-2">
              <Heart className="h-5 w-5 text-pink-300" />
              <h3 className="font-semibold">Favorite Category</h3>
            </div>
            <p className="text-2xl font-bold capitalize">{favorite_category}</p>
          </div>
        </div>

        {/* Peak Time */}
        <div className="rounded-lg bg-white/10 p-6 backdrop-blur-sm">
          <div className="mb-2 flex items-center gap-2">
            <Trophy className="h-5 w-5 text-yellow-300" />
            <h3 className="font-semibold">Peak Month</h3>
          </div>
          <p className="text-2xl font-bold">{most_active_month}</p>
          <p className="mt-1 text-sm">This was your most active month!</p>
        </div>

        {/* Footer */}
        <div className="pt-4 text-center text-sm text-white/80">
          <p>Keep capturing amazing events!</p>
          <p className="mt-1">Generated by Soonlist</p>
        </div>
      </div>
    </div>
  );
};

interface Props {
  params: { userName: string };
}

// Example usage:
const Page = ({ params }: Props) => {
  const userName = params.userName;

  if (!userName || !dataForUsersFor2024[userName]) {
    return <div>No data for this user</div>;
  }

  const userData = dataForUsersFor2024[userName];

  //   const userData = {
  //     user_id: "user_2ZFNoiajf80Q4ZiTQj8hAgatRCt",
  //     username: "jaronheard",
  //     percentile: "100.0",
  //     active_days: "153",
  //     total_events_captured: "252",
  //     unique_event_types: "22",
  //     most_active_month: "June",
  //     favorite_type: "concert",
  //     favorite_category: "music",
  //     events_followed: "28"
  //   };

  return <YearInReviewCard {...userData} />;
};

export default Page;
