import React from "react";
import {
  Calendar,
  Crown,
  Heart,
  Sparkles,
  Star,
  Trophy,
  Users,
} from "lucide-react";

const YearInReviewCard = () => {
  return (
    <div className="mx-auto max-w-2xl rounded-xl bg-gradient-to-br from-purple-600 to-blue-600 p-8 text-white shadow-xl">
      <div className="space-y-6">
        {/* Header */}
        <div className="space-y-2 text-center">
          <div className="flex items-center justify-center gap-2">
            <Sparkles className="h-6 w-6" />
            <h1 className="text-3xl font-bold">2024 Year in Review</h1>
            <Sparkles className="h-6 w-6" />
          </div>
          <p className="text-xl font-medium">@joshcarr</p>
        </div>

        {/* Capturer Status */}
        <div className="rounded-lg bg-white/10 p-6 backdrop-blur-sm">
          <div className="mb-4 flex items-center gap-2">
            <Crown className="h-6 w-6 text-yellow-300" />
            <h2 className="text-2xl font-bold">Top 3% Capturer!</h2>
          </div>
          <p className="text-lg">
            You're in the top{" "}
            <span className="font-bold text-yellow-300">3%</span> of all
            capturers this year
          </p>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-2 gap-4">
          <div className="rounded-lg bg-white/10 p-4 backdrop-blur-sm">
            <div className="mb-2 flex items-center gap-2">
              <Calendar className="h-5 w-5" />
              <h3 className="font-semibold">Events Captured</h3>
            </div>
            <p className="text-3xl font-bold">126</p>
          </div>

          <div className="rounded-lg bg-white/10 p-4 backdrop-blur-sm">
            <div className="mb-2 flex items-center gap-2">
              <Users className="h-5 w-5" />
              <h3 className="font-semibold">Active Days</h3>
            </div>
            <p className="text-3xl font-bold">94</p>
          </div>
        </div>

        {/* Preferences */}
        <div className="space-y-4 rounded-lg bg-white/10 p-6 backdrop-blur-sm">
          <div>
            <div className="mb-2 flex items-center gap-2">
              <Star className="h-5 w-5 text-yellow-300" />
              <h3 className="font-semibold">Your Go-To Event Type</h3>
            </div>
            <p className="text-2xl font-bold capitalize">Concert</p>
          </div>

          <div>
            <div className="mb-2 flex items-center gap-2">
              <Heart className="h-5 w-5 text-pink-300" />
              <h3 className="font-semibold">Favorite Category</h3>
            </div>
            <p className="text-2xl font-bold capitalize">Music</p>
          </div>
        </div>

        {/* Peak Time */}
        <div className="rounded-lg bg-white/10 p-6 backdrop-blur-sm">
          <div className="mb-2 flex items-center gap-2">
            <Trophy className="h-5 w-5 text-yellow-300" />
            <h3 className="font-semibold">Peak Month</h3>
          </div>
          <p className="text-2xl font-bold">October</p>
          <p className="mt-1 text-sm">This was your most active month!</p>
        </div>

        {/* Footer */}
        <div className="pt-4 text-center text-sm text-white/80">
          <p>Keep capturing amazing events!</p>
          <p className="mt-1">Generated by Soonlist</p>
        </div>
      </div>
    </div>
  );
};

export default YearInReviewCard;
