packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Dev tooling
  eslint: ^9.1.1
  prettier: ^3.2.5
  tailwindcss: ^3.4.3
  typescript: ~5.9.2

  # Backend
  convex: 1.31.2
  "@convex-dev/migrations": ^0.2.9
  "@convex-dev/workflow": ^0.2.4
  "@convex-dev/workpool": ^0.2.10
  "convex-helpers": ^0.1.89

  # Misc
  zod: ^3.23.0
  superjson: 2.2.1
  nanoid: ^5.0.7
  clsx: ^2.1.0
  uuid: ^9.0.1

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.74.7
  "@tanstack/react-query-devtools": ^5.74.7
  "@tanstack/query-async-storage-persister": ^5.74.7
  "@tanstack/react-query-persist-client": ^5.74.7
  "@trpc/client": 11.0.0-rc.364
  "@trpc/react-query": 11.0.0-rc.364
  "@trpc/server": 11.0.0-rc.364

  # React & Next.js
  next: 15.1.9
  "server-only": ^0.0.1

  # Database
  "drizzle-orm": ^0.30.10
  "drizzle-kit": ^0.21.1
  "drizzle-zod": ^0.5.1
  "@planetscale/database": ^1.18.0
  mysql2: ^3.9.7

  # Authentication & Security
  "@clerk/nextjs": ^6.20.0
  "@clerk/clerk-expo": ^2.11.8
  "@clerk/backend": ^1.33.0

  # Monitoring & Analytics
  "@sentry/nextjs": ^8.35.0
  "@sentry/node": ^8.35.0
  "@sentry/react-native": ~7.11.0
  "posthog-js": ^1.240.5
  "posthog-node": ^4.17.1
  "posthog-react-native": ^4.17.3
  langfuse: ^3.11.0

  # Environment & Config
  "@t3-oss/env-nextjs": ^0.10.1
  "@t3-oss/env-core": ^0.10.0
  dotenv: ^16.4.4
  "dotenv-cli": ^7.4.1
  "dotenv-expand": ^11.0.6

  # UI Libraries
  "lucide-react": ^0.373.0
  cmdk: ^0.2.0

  # Expo & React Native Core
  expo: 55.0.0-preview.12
  "expo-router": 55.0.0-preview.9
  "expo-constants": ~55.0.6
  "expo-dev-client": ~55.0.7
  "expo-image": ~55.0.4
  "expo-video": ~55.0.8
  "expo-secure-store": ~55.0.7
  "expo-status-bar": ~55.0.3
  "@expo/metro-runtime": ~55.0.6
  "@expo/ui": ~55.0.0-preview.7
  "react-native": 0.83.2
  "react-native-reanimated": ~4.2.1
  "react-native-worklets": ~0.7.1
  "react-native-gesture-handler": ~2.30.0
  "react-native-safe-area-context": ^5.6.2
  "react-native-screens": ~4.23.0
  "react-native-svg": 15.15.3
  nativewind: ~4.2.1

  # Additional Expo packages
  "expo-apple-authentication": ~55.0.7
  "expo-application": ~55.0.7
  "expo-asset": ~55.0.6
  "expo-auth-session": ~55.0.5
  "expo-background-task": ~55.0.7
  "expo-blur": ~55.0.7
  "expo-build-properties": ~55.0.8
  "expo-calendar": ~55.0.7
  "expo-clipboard": ~55.0.7
  "expo-device": ~55.0.8
  "expo-file-system": ~55.0.8
  "expo-haptics": ~55.0.7
  "expo-image-manipulator": ~55.0.8
  "expo-image-picker": ~55.0.8
  "expo-linear-gradient": ~55.0.7
  "expo-linking": ~55.0.6
  "expo-localization": ~55.0.7
  "expo-location": ~19.0.10
  "expo-media-library": ~55.0.8
  "expo-notifications": ~55.0.9
  "expo-splash-screen": ~55.0.8
  "expo-store-review": ~55.0.7
  "expo-task-manager": ~55.0.8
  "expo-updates": ~55.0.10
  "expo-web-browser": ~55.0.8
  "expo-quick-actions": ~6.0.0

  # React Native Additional packages
  "@react-native-async-storage/async-storage": ~2.2.0
  "@react-native-community/datetimepicker": 8.6.0
  "@react-native-community/netinfo": 11.5.2
  "react-native-appsflyer": ^6.15.3
  "@react-native-menu/menu": 2.0.0
  "react-native-ios-context-menu": 3.2.0
  "react-native-ios-utilities": 5.2.0
  "react-native-keyboard-controller": 1.20.7
  "react-native-modal": 14.0.0-rc.1
  "react-native-onesignal": ^5.2.8
  "react-native-purchases-ui": ^8.9.1
  "react-native-qrcode-svg": ^6.3.0
  "posthog-react-native-session-replay": ^1.2.3

  # Third-party integrations
  "@intercom/intercom-react-native": ^8.5.0
  "@bacons/apple-targets": ^0.2.1
  "onesignal-expo-plugin": ^2.0.3

  # Payment & Subscriptions
  stripe: ^15.9.0
  "react-native-purchases": ^8.9.1

  # File Upload
  "@bytescale/sdk": ^3.34.0
  "@bytescale/upload-widget-react": ^4.16.0

  # Image Processing
  "@jsquash/resize": ^2.1.0
  "@jsquash/webp": ^1.5.0

  # Babel & Compilation
  "@babel/core": ^7.26.0
  "@babel/preset-env": ^7.24.4
  "@babel/runtime": ^7.24.4

  # State Management
  zustand: 4.5.5

  # List Performance
  "@legendapp/list": ^2.0.4

  # Node Types
  "@types/node": 20.12.7
  "@types/uuid": ^9.0.8
  "@types/babel__core": ^7.20.5
  "@types/invariant": ^2.2.37
  "@types/ssrf-req-filter": ^1.1.1

  # Build Tools
  turbo: ^2.5.3
  "@turbo/gen": ^2.5.3
  jiti: ^1.21.3
  postcss: ^8.4.38

  # Web-specific packages
  "add-to-calendar-button-react": ^2.6.13
  "react-easy-sort": ^1.6.0
  "react-image-crop": ^11.0.5
  "react-qr-code": ^2.0.15
  "react-timezone-select": ^3.2.0
  "recharts": ^2.15.0
  "svix": ^1.15.0
  "timezone-soft": ^1.5.2
  "yet-another-react-lightbox": ^3.21.7

  # Development tools
  "@tailwindcss/typography": ^0.5.10
  "concurrently": ^8.2.2
  "encoding": ^0.1.13
  "eslint-plugin-path": ^1.2.4
  "eslint-plugin-tailwindcss": ^3.14.0
  "eslint-plugin-react-compiler": 19.1.0-rc.1
  "expo-atlas": ^0.4.3

  # ESLint plugins
  "@next/eslint-plugin-next": ^14.2.0
  "eslint-config-turbo": ^1.13.2
  "eslint-plugin-import": ^2.29.1
  "eslint-plugin-jsx-a11y": ^6.8.0
  "eslint-plugin-react": ^7.34.1
  "eslint-plugin-react-hooks": 5.1.0-beta-1beb73de0f-20240503
  "typescript-eslint": ^8.32.1

  # Prettier plugins
  "@ianvs/prettier-plugin-sort-imports": ^4.2.1
  "prettier-plugin-tailwindcss": ^0.5.13

  # Tailwind
  "tailwindcss-animate": ^1.0.7

  # UI Components (Radix)
  "@hookform/resolvers": ^3.3.4
  "@radix-ui/react-accordion": ^1.2.1
  "@radix-ui/react-aspect-ratio": ^1.1.0
  "@radix-ui/react-dialog": ^1.1.2
  "@radix-ui/react-dropdown-menu": ^2.1.2
  "@radix-ui/react-label": ^2.1.0
  "@radix-ui/react-navigation-menu": ^1.2.1
  "@radix-ui/react-popover": ^1.1.2
  "@radix-ui/react-scroll-area": ^1.2.0
  "@radix-ui/react-select": ^2.1.2
  "@radix-ui/react-separator": ^1.1.0
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-switch": ^1.1.1
  "@radix-ui/react-tabs": ^1.1.1
  "@radix-ui/react-toast": ^1.2.2
  "@radix-ui/react-toggle": ^1.1.0

  # Other UI utilities
  "class-variance-authority": ^0.7.0
  "embla-carousel-autoplay": ^8.3.0
  "embla-carousel-react": ^8.3.0
  "next-themes": ^0.3.0
  "react-hook-form": ^7.51.1
  "sonner": ^1.4.41
  "tailwind-merge": ^2.2.2
  "vaul": ^0.9.1
  burnt: ^0.13.0
  "react-native-notifier": ^2.0.0
  "zeego": 3.0.6

  # API & AI
  "@ai-sdk/anthropic": ^0.0.50
  "@ai-sdk/openai": ^0.0.18
  "@vercel/functions": ^1.0.2
  "ai": ^3.1.22
  "expo-server-sdk": ^3.10.0

  # Date/Time utilities
  "date-fns": ^3.6.0
  "date-fns-tz": ^3.2.0
  "moment-timezone": ^0.5.47

  # Other utilities
  "@js-temporal/polyfill": ^0.4.4
  "zod-to-json-schema": ^3.23.0
  "p-map": ^7.0.3

catalogs:
  react19:
    react: 19.2.0
    react-dom: 19.2.0
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.2.0

onlyBuiltDependencies:
  - esbuild
