packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Dev tooling
  eslint: ^9.1.1
  prettier: ^3.2.5
  tailwindcss: ^3.4.3
  typescript: ^5.8.3

  # Misc
  zod: ^3.23.0
  superjson: 2.2.1
  nanoid: ^5.0.7
  clsx: ^2.1.0
  uuid: ^9.0.1

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.74.7
  "@tanstack/react-query-devtools": ^5.74.7
  "@tanstack/query-async-storage-persister": ^5.74.7
  "@tanstack/react-query-persist-client": ^5.74.7
  "@trpc/client": 11.0.0-rc.364
  "@trpc/react-query": 11.0.0-rc.364
  "@trpc/server": 11.0.0-rc.364

  # React & Next.js
  next: 15.1.8
  "server-only": ^0.0.1

  # Database
  "drizzle-orm": ^0.30.10
  "drizzle-kit": ^0.21.1
  "drizzle-zod": ^0.5.1
  "@planetscale/database": ^1.18.0
  mysql2: ^3.9.7

  # Authentication & Security
  "@clerk/nextjs": ^5.0.8
  "@clerk/clerk-expo": ^1.1.0
  "@clerk/clerk-sdk-node": ^5.0.5

  # Monitoring & Analytics
  "@sentry/nextjs": ^8.35.0
  "@sentry/node": ^8.35.0
  "@sentry/react-native": ^6.10.0
  "posthog-js": ^1.240.5
  "posthog-node": ^4.17.1
  "posthog-react-native": ^3.15.2
  langfuse: ^3.11.0

  # Environment & Config
  "@t3-oss/env-nextjs": ^0.10.1
  "@t3-oss/env-core": ^0.10.0
  dotenv: ^16.4.4
  "dotenv-cli": ^7.4.1
  "dotenv-expand": ^11.0.6

  # UI Libraries
  "lucide-react": ^0.373.0
  cmdk: ^0.2.0

  # Expo & React Native
  expo: ~53.0.9
  "expo-router": ~5.0.7
  "expo-constants": ~17.1.6
  "expo-dev-client": ~5.1.8
  "expo-image": ~2.1.7
  "expo-secure-store": ^14.2.3
  "expo-status-bar": ~2.2.3
  "react-native": ~0.79.2
  "react-native-reanimated": ~3.17.5
  "react-native-gesture-handler": ~2.24.0
  "react-native-safe-area-context": ~5.4.0
  "react-native-screens": ~4.10.0
  "react-native-svg": 15.11.2
  nativewind: ~4.1.23

  # Payment & Subscriptions
  stripe: ^15.9.0
  "react-native-purchases": ^8.9.1

  # File Upload
  "@bytescale/sdk": ^3.34.0
  "@bytescale/upload-widget-react": ^4.16.0

  # Babel & Compilation
  "@babel/core": ^7.26.0
  "@babel/preset-env": ^7.24.4
  "@babel/runtime": ^7.24.4

  # State Management
  zustand: 4.5.5

  # Node Types
  "@types/node": 20.12.7
  "@types/uuid": ^9.0.8

  # Build Tools
  turbo: ^2.0.4
  "@turbo/gen": ^2.0.4
  jiti: ^1.21.3
  postcss: ^8.4.38

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": 19.1.5
    "@types/react-dom": 19.1.5

onlyBuiltDependencies:
  - esbuild
