name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: Create and ensure write permissions on .gitignore
        shell: bash
        working-directory: apps/expo
        run: |
          touch .gitignore
          chmod +w .gitignore

      - name: Generate typed routes for Expo Router
        working-directory: apps/expo
        run: npx expo customize tsconfig.json

      - name: Lint
        run: pnpm lint && pnpm lint:ws

  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Format
        run: pnpm format

  typecheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Create and ensure write permissions on .gitignore
        shell: bash
        working-directory: apps/expo
        run: |
          touch .gitignore
          chmod +w .gitignore

      - name: Generate typed routes for Expo Router
        working-directory: apps/expo
        run: npx expo customize tsconfig.json

      - name: Show TypeScript version
        run: npx tsc --version

      - name: Clean TypeScript cache
        run: |
          find . -name "*.tsbuildinfo" -delete
          find . -name ".turbo" -type d -exec rm -rf {} +

      - name: Typecheck
        run: pnpm typecheck
        env:
          DEBUG: "*"
