name: Sync main branch to preview

on:
  push:
    branches:
      - main

jobs:
  mirror-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: zofrex/mirror-branch@v1
        with:
          target-branch: preview
